---
title: "Manchester_0313"
output: 
  pdf_document:
    latex_engine: xelatex
date: "2026-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Library, include = FALSE}
library(sf)        # 空间数据读写
library(dplyr)     # 数据操作
library(mapview)   # 交互式地图（仅用于中小规模）
library(spatstat) # 网络数据结构
library(spatstat.Knet)
library(stlnpp)
library(plot3D)
```

```{r LoadingData, include=FALSE}

XSeverity_manCity <- readRDS("~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/0313Fri/CM_data/XSeverity_manCity.rds")

net <- readRDS("~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/Manchester/GM_data/gm_net.rds")

cm_boundary <- st_read("~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/0313Fri/CM_data/cm_boundary.shp")

roads_psp <- readRDS("~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/Manchester/GM_data/gm_roads_psp.rds")

acc <- read.csv("~/Library/Mobile Documents/com~apple~CloudDocs/DataSet/Manchester_OriginalData/STATS19AccDataJan2010Dec2021forGMServers.csv")


acc$datetime <- as.POSIXct(paste(acc$OutputDate, acc$OutputTime),
                    format="%d/%m/%Y %H:%M", tz="Europe/London")

t_all <- acc$datetime 
t_all_num <- as.numeric(t_all)
tmin <- min(t_all_num, na.rm=TRUE)
tmax <- max(t_all_num, na.rm=TRUE)
acc$datetime <- (t_all_num - tmin)/(tmax - tmin)


acc_sf <- st_as_sf(
  acc,
  coords = c("Easting", "Northing"),
  crs = 27700,
  remove = FALSE
)
acc_sf <- st_filter(acc_sf, cm_boundary, .predicate = st_within) 

gm_win <- as.owin(cm_boundary)
```

```{r}
names(acc_sf)
str(acc_sf$datetime)
summary(acc_sf$datetime)

```

```{r pointsAndsave(withT)}
# classify by Severity(1-3)

pts_sf <- vector( "list", 3)
XSeverity_manST <- vector ("list", 3)
T2 <- vector("list", 3)


for (i in seq_len(3)){
  pts_sf[[i]] <- acc_sf [acc_sf$Severity == i, ]
  
  # sf -> ppp（窗口必须是 gm_win）
  xy <- sf::st_coordinates(pts_sf[[i]])
  
  t01 <- pts_sf[[i]]$datetime
  # 投影到最近道路线段（确保点落在网络上）
  acc_pp <- spatstat.geom::ppp(x = xy[,1], y = xy[,2], 
                               window = gm_win, 
                               marks = t01, 
                               checkdup = FALSE) 
  
  
  prj <- spatstat.geom::project2segment(acc_pp, roads_psp)
  acc_snap <- prj$Xproj   # 已经“贴”到道路上的 ppp
  
  
  # LNPP
  L <- net[gm_win, clip = TRUE, drop = TRUE]
  X <- spatstat.linnet::lpp(acc_snap, L)
  
  
  T2[[i]] <- marks(X)
  X_st <- stlpp(X, L = L, T = T2[[i]])
  
  
  X_st
  XSeverity_manST[[i]] <- X_st
}


dir.create("~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/0313Fri/CM_data(ST)", showWarnings = FALSE)
# save
saveRDS(XSeverity_manST, file = "~/Library/Mobile Documents/com~apple~CloudDocs/Rstudio/0313Fri/CM_data(ST)/XSeverity_manST.rds")
```

```{r ,fig.width=8, fig.height=6,,dpi = 600}
plot(XSeverity_manST[[1]])
X <- XSeverity_manST[[1]]

L  <- X$domain

x <- X$data$x
y <- X$data$y

length(x); length(y)          # 应该都是 137
head(x); head(y)

lpp_X <- spatstat.linnet::lpp(x = x, y = y, L = L)

spatstat.geom::npoints(lpp_X) # 应该是 137
plot(L, main="network"); points(x, y, pch=16, cex=0.4, col="red")

X_st <- stlpp(lpp_X, T = T2[[1]], L = L)

k <- STLK(X_st, r = NULL, t = NULL, nxy = 10)
```

```{r ,fig.width=8, fig.height=6,,dpi = 600}
X <- XSeverity_manST[[1]]
is.null(T2[[1]])
length(T2[[1]])
class(T2[[1]])
spatstat.geom::npoints(X)
str(marks(XSeverity_manST[[1]]))
c(class(X), is.null(X$time))
str(X$T)
names(X)
```
