---
title: "Manchester_Multitype"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 12,
  fig.height = 8,
  dpi = 600
)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


project_root <- getwd()
knitr::opts_knit$set(root.dir = project_root)
```

```{r Library, include = FALSE}
library(sf)        # 空间数据读写
library(dplyr)     # 数据操作
library(mapview)   # 交互式地图（仅用于中小规模）
library(spatstat) # 网络数据结构
library(spatstat.Knet)

x_sub_path <- "0313Fri/CM_data/X_sub.rds"
X_sub <- readRDS(x_sub_path)

L <- domain(X_sub[[1]])

```

```{r subnetwork, fig.width=8, fig.height=6,,dpi = 600}

# 取该对象的网络与窗口
L <- domain(X_sub[[1]])

op <- par(mar=c(1,1,1,1))

#pdf("Man_map.pdf",width=8, height=6)

plot(L, main="Accident with different severity on Manchester city center", col="grey70", lwd=0.4)


plot(as.ppp(X_sub[[3]]), add=TRUE, cols="green", pch=16, cex=0.5)
plot(as.ppp(X_sub[[2]]), add=TRUE, cols="blue", pch=16, cex=0.5)
plot(as.ppp(X_sub[[1]]), add=TRUE, cols="red", pch=16, cex=0.5)



usr <- par("usr")  # c(xmin, xmax, ymin, ymax)

x0 <- usr[1] + 0.08*(usr[2]-usr[1])
y0 <- usr[3] + 0.08*(usr[4]-usr[3])

sb <- spatstat.geom::yardstick(
  x0 = x0, y0 = y0,
  x1 = x0 + 1000, y1 = y0,   # 1000m measuring scale
  txt = "1000 m"
)

plot(sb, add = TRUE)

par(op)

#dev.off()
```

```{r simulationPrepare}

#N1\N2\N3 uniformly random

xy_all <- data.frame()
for (i in seq_len(length(X_sub))) {
  xy_i <- as.data.frame(X_sub[[i]])[, c("x", "y")]
  xy_i$severity <- i
  xy_all <- rbind(xy_all, xy_i)
}

X <- as.lpp(
  x = xy_all$x,
  y = xy_all$y,
  L = L
)
marks(X) <- data.frame(severity = xy_all$severity)

npoints(X)
nsegments(L)
round(volume(L), 2)

```

```{r L_sub}

road_lines <- as.psp(L)

segment_id_at_events <- as.data.frame(X)$seg
accident_count <- tabulate(segment_id_at_events, nbins = nsegments(L))

S <- as.integer(accident_count > 0)

seg <- data.frame(
  seg_id = seq_len(nsegments(L)),
  S = S,
  label = ifelse(S == 1, "P", "U")
)


p_seg <- seg$seg_id[seg$S == 1]
L_sub <- thinNetwork(L, retainedges = p_seg)

```

```{r simulation1}

X_random <- vector ("list", 3)

for (i in seq_len(3)) {
  X_random[[i]] <- runiflpp(
    n = npoints(X_sub[[i]]),
    L = L
    )
}

cols <- adjustcolor(grDevices::hcl.colors(3, "Dark 3"), alpha.f = 0.2)
cols <- c("red","blue","green")

r_grid <- seq(0, 2000, length = 50) # meter

#op <- par(mfrow = c(1, 2), mar = c(0.5, 0.5, 2, 0.5))

plot(L, main="Simulation1 N_1-3", col="grey70", lwd=0.4)

plot(as.ppp(X_random[[3]]), add=TRUE, cols="green", pch=16, cex=0.5)
plot(as.ppp(X_random[[2]]), add=TRUE, cols="blue", pch=16, cex=0.5)
plot(as.ppp(X_random[[1]]), add=TRUE, cols="red", pch=16, cex=0.5)


for(i in seq_len(3)){
  
  if (i==1){
    Kb <- Knet(X_random[[i]], r = r_grid)
    plot(Kb, legend = FALSE, lwd = 2, col = cols[i], main = "")
  }
  else if(i==2){
    Kb <- Knet(X_random[[i]], r = r_grid)
    K2 <- Kb
    lines(Kb$r, Kb$est, lty=1, col = cols[i])
  }
  else {
    Kb <- Knet(X_random[[i]], r = r_grid)
    K3 <- Kb
    lines(Kb$r, Kb$est, lty=1, col = cols[i])
  }
}

legend("topleft",
       legend = paste0("SimNo=", 1:3),
       col = cols, lwd = 2, bty = "n")

#par(op)
```

```{r Sim1-Kcross_Xrandom}
X_random_multi <- superimpose(
  sev1 = unmark(X_random[[1]]),
  sev2 = unmark(X_random[[2]]),
  sev3 = unmark(X_random[[3]])
)
X_random_label <- X_random_multi #for random label

marks(X_random_multi) <- factor(
  marks(X_random_multi),
  levels = c("sev1", "sev2", "sev3")
)

table(marks(X_random_multi))

K12_random <- linearKcross(
  X_random_multi,
  i = "sev1",
  j = "sev2",
  r = r_grid
)

K13_random <- linearKcross(
  X_random_multi,
  i = "sev1",
  j = "sev3",
  r = r_grid
)

K23_random <- linearKcross(
  X_random_multi,
  i = "sev2",
  j = "sev3",
  r = r_grid
)

# Plot the three cross-K functions
op <- par(mar = c(4, 4, 2, 1))

ylim_cross <- range(
  K12_random$est,
  K13_random$est,
  K23_random$est,
  K12_random$theo
)

plot(
  K12_random$r,
  K12_random$est,
  type = "l",
  lwd = 2,
  col = "purple",
  xlab = "Network distance r (m)",
  ylab = expression(K[cross](r)),
  main = "Cross-K: random severity types",
  ylim = ylim_cross
)

lines(K13_random$r, K13_random$est, lwd = 2, col = "orange")
lines(K23_random$r, K23_random$est, lwd = 2, col = "darkgreen")


lines(
  K12_random$r,
  K12_random$theo,
  lty = 2,
  col = "grey40"
)

legend(
  "topleft",
  legend = c("K12_random", "K13_random",
             "K23_random", "Homogeneous Pois: r"),
  col = c("purple", "orange", "darkgreen", "grey40"),
  lwd = c(2, 2, 2, 1),
  lty = c(1, 1, 1, 2),
  bty = "n"
)

par(op)
```

```{r Sim1RandomLabel}
#####################Random Labelling########
X_base <- X_random_multi

severity_levels <- c("sev1", "sev2", "sev3")

marks(X_base) <- factor(
  marks(X_base),
  levels = severity_levels
)

# Observed cross-K functions before randomising the labels
K12_obs <- linearKcross(X_base, i = "sev1", j = "sev2", r = r_grid)
K13_obs <- linearKcross(X_base, i = "sev1", j = "sev3", r = r_grid)
K23_obs <- linearKcross(X_base, i = "sev2", j = "sev3", r = r_grid)

# Number of random-labelling simulations
B <- 10

K12_sim <- matrix(NA_real_, nrow = length(r_grid), ncol = B)
K13_sim <- matrix(NA_real_, nrow = length(r_grid), ncol = B)
K23_sim <- matrix(NA_real_, nrow = length(r_grid), ncol = B)


for (b in seq_len(B)) {
  
  # Copy the locations, then shuffle only their labels
  X_random_label <- X_base
  
  random_marks <- sample(
    as.character(marks(X_base)),
    size = npoints(X_base),
    replace = FALSE
  )
  
  marks(X_random_label) <- factor(
    random_marks,
    levels = severity_levels
  )
  
  K12_b <- linearKcross(
    X_random_label,
    i = "sev1",
    j = "sev2",
    r = r_grid
  )
  
  K13_b <- linearKcross(
    X_random_label,
    i = "sev1",
    j = "sev3",
    r = r_grid
  )
  
  K23_b <- linearKcross(
    X_random_label,
    i = "sev2",
    j = "sev3",
    r = r_grid
  )
  
  K12_sim[, b] <- K12_b$est
  K13_sim[, b] <- K13_b$est
  K23_sim[, b] <- K23_b$est
}

# 95% pointwise envelopes
K12_env <- apply(K12_sim, 1, quantile, probs = c(0.025, 0.975))
K13_env <- apply(K13_sim, 1, quantile, probs = c(0.025, 0.975))
K23_env <- apply(K23_sim, 1, quantile, probs = c(0.025, 0.975))
```

```{r Sim1-Plot}
op <- par(mfrow = c(1, 1), mar = c(4, 4, 2, 1))

plot(
  NULL,
  xlim = range(r_grid),
  ylim = range(K12_env, K12_obs$est),
  xlab = "Network distance r (m)",
  ylab = expression(K[12](r)),
  main = "Random labelling: 1 vs 2"
)

polygon(
  c(r_grid, rev(r_grid)),
  c(K12_env[1, ], rev(K12_env[2, ])),
  col = adjustcolor("grey70", alpha.f = 0.5),
  border = NA
)

lines(K12_obs$r, K12_obs$est, lwd = 2, col = "purple")
lines(K12_obs$r, K12_obs$theo, lty = 2, col = "gray40")

plot(
  NULL,
  xlim = range(r_grid),
  ylim = range(K13_env, K13_obs$est),
  xlab = "Network distance r (m)",
  ylab = expression(K[13](r)),
  main = "Random labelling: 1 vs 3"
)

polygon(
  c(r_grid, rev(r_grid)),
  c(K13_env[1, ], rev(K13_env[2, ])),
  col = adjustcolor("grey70", alpha.f = 0.5),
  border = NA
)

lines(K13_obs$r, K13_obs$est, lwd = 2, col = "orange")
lines(K13_obs$r, K13_obs$theo, lty = 2, col = "gray40")

plot(
  NULL,
  xlim = range(r_grid),
  ylim = range(K23_env, K23_obs$est),
  xlab = "Network distance r (m)",
  ylab = expression(K[23](r)),
  main = "Random labelling: 2 vs 3"
)

polygon(
  c(r_grid, rev(r_grid)),
  c(K23_env[1, ], rev(K23_env[2, ])),
  col = adjustcolor("grey70", alpha.f = 0.5),
  border = NA
)

lines(K23_obs$r, K23_obs$est, lwd = 2, col = "darkgreen")
lines(K23_obs$r, K23_obs$theo, lty = 2, col = "gray40")

par(op)
```

```{r simulation2}
X_Lsub <- vector ("list", 3)

for (i in seq_len(3)) {
  X_Lsub[[i]] <- runiflpp(
    n = npoints(X_sub[[i]]),
    L = L_sub
  )
}

XLsub_on_L <- vector("list", 3)

for (i in seq_len(3)) {
  point_data <- as.data.frame(X_Lsub[[i]])
  XLsub_on_L[[i]] <- lpp(
    point_data[, c("x", "y")],
    L = L
  )
}

cols <- adjustcolor(grDevices::hcl.colors(3, "Dark 3"), alpha.f = 0.2)
cols <- c("red","blue","green")

r_grid <- seq(0, 2000, length = 50) # meter

#op <- par(mfrow = c(1, 2), mar = c(0.5, 0.5, 2, 0.5))

plot(L, main="Simulation1 N_1-3", col="grey70", lwd=0.4)

plot(as.ppp(XLsub_on_L[[3]]), add=TRUE, cols="green", pch=16, cex=0.5)
plot(as.ppp(XLsub_on_L[[2]]), add=TRUE, cols="blue", pch=16, cex=0.5)
plot(as.ppp(XLsub_on_L[[1]]), add=TRUE, cols="red", pch=16, cex=0.5)

for(i in seq_len(3)){
  
  if (i==1){
    Kb <- Knet(XLsub_on_L[[i]], r = r_grid)
    plot(Kb, legend = FALSE, lwd = 2, col = cols[i], main = "")
  }
  else if(i==2){
    Kb <- Knet(XLsub_on_L[[i]], r = r_grid)
    K2 <- Kb
    lines(Kb$r, Kb$est, lty=1, col = cols[i])
  }
  else {
    Kb <- Knet(XLsub_on_L[[i]], r = r_grid)
    K3 <- Kb
    lines(Kb$r, Kb$est, lty=1, col = cols[i])
  }
}

legend("topleft",
       legend = paste0("Severity=", 1:3),
       col = cols, lwd = 2, bty = "n")

#par(op)
```

```{r Sim2-Kcross_XLsub}
X_Lsub_multi <- superimpose(
  sev1 = unmark(XLsub_on_L[[1]]),
  sev2 = unmark(XLsub_on_L[[2]]),
  sev3 = unmark(XLsub_on_L[[3]])
)

marks(X_Lsub_multi) <- factor(
  marks(X_Lsub_multi),
  levels = c("sev1", "sev2", "sev3")
)

table(marks(X_Lsub_multi))

K12_Lsub <- linearKcross(
  X_Lsub_multi,
  i = "sev1",
  j = "sev2",
  r = r_grid
)

K13_Lsub <- linearKcross(
  X_Lsub_multi,
  i = "sev1",
  j = "sev3",
  r = r_grid
)

K23_Lsub <- linearKcross(
  X_Lsub_multi,
  i = "sev2",
  j = "sev3",
  r = r_grid
)

# Plot the three cross-K functions
op <- par(mar = c(4, 4, 2, 1))

ylim_cross <- range(
  K12_Lsub$est,
  K13_Lsub$est,
  K23_Lsub$est,
  K12_Lsub$theo
)

plot(
  K12_Lsub$r,
  K12_Lsub$est,
  type = "l",
  lwd = 2,
  col = "purple",
  xlab = "Network distance r (m)",
  ylab = expression(K[cross](r)),
  main = "Cross-K: random severity types",
  ylim = ylim_cross
)

lines(K13_Lsub$r, K13_Lsub$est, lwd = 2, col = "orange")
lines(K23_Lsub$r, K23_Lsub$est, lwd = 2, col = "darkgreen")


lines(
  K12_Lsub$r,
  K12_Lsub$theo,
  lty = 2,
  col = "grey40"
)

legend(
  "topleft",
  legend = c("K12_Lsub", "K13_Lsub",
             "K23_Lsub", "Homogeneous Pois: r"),
  col = c("purple", "orange", "darkgreen", "grey40"),
  lwd = c(2, 2, 2, 1),
  lty = c(1, 1, 1, 2),
  bty = "n"
)

par(op)
```
