---
title: "Manchester_Multitype"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
run_heavy <- FALSE
```

```{r Library, include = FALSE}
library(sf)        # 空间数据读写
library(dplyr)     # 数据操作
library(mapview)   # 交互式地图（仅用于中小规模）
library(spatstat) # 网络数据结构
library(spatstat.Knet)

```

```{r LoadingData, include=FALSE}

XSeverity_manCity <- readRDS("0313Fri/CM_data/XSeverity_manCity.rds")

net <- readRDS("Manchester/GM_data/gm_net.rds")

cm_boundary <- st_read("0313Fri/CM_data/cm_boundary.shp")

roads_psp <- readRDS("Manchester/GM_data/gm_roads_psp.rds")

acc <- read.csv("DataSet/Manchester_OriginalData/STATS19AccDataJan2010Dec2021forGMServers.csv")

acc_sf <- st_as_sf(
  acc,
  coords = c("Easting", "Northing"),
  crs = 27700,
  remove = FALSE
)

gm_win <- as.owin(cm_boundary)
```

```{r pointsAndsave,include=FALSE, cache=TRUE}
# classify by Severity(1-3)

pts_sf <- vector( "list", 3)
XSeverity_manCity <- vector ("list", 3)


for (i in seq_len(3)){
  pts_sf[[i]] <- acc_sf [acc_sf$Severity == i, ]
  
  # sf -> ppp（窗口必须是 gm_win）
  xy <- sf::st_coordinates(pts_sf[[i]])
  acc_pp <- spatstat.geom::ppp(x = xy[,1], y = xy[,2], window = gm_win, checkdup = FALSE)

  # 投影到最近道路线段（确保点落在网络上）
 
  prj <- spatstat.geom::project2segment(acc_pp, roads_psp)
  acc_snap <- prj$Xproj   # 已经“贴”到道路上的 ppp

  
  # LNPP
  L <- net[gm_win, clip = TRUE, drop = TRUE]
  X <- spatstat.linnet::lpp(acc_snap, L)
  
  X
  XSeverity_manCity[[i]] <- X
}


dir.create("0313Fri/CM_data", showWarnings = FALSE)
# save
saveRDS(XSeverity_manCity, file = "0313Fri/CM_data/XSeverity_manCity.rds")
```

```{r ,fig.width=8, fig.height=6,,dpi = 600, include=FALSE}
plot(acc_sf)

# 取该对象的网络与窗口
L <- domain(XSeverity_manCity[[1]])

# 只画网络所在的最小包围矩形（减少空白）
op <- par(mar=c(1,1,1,1))
plot(L, main="3 types of accidents on Manchester", col="grey70", lwd=0.4)

plot(as.ppp(XSeverity_manCity[[3]]), add=TRUE, cols="green", pch=16, cex=0.5)
plot(as.ppp(XSeverity_manCity[[2]]), add=TRUE, cols="blue", pch=16, cex=0.5)
plot(as.ppp(XSeverity_manCity[[1]]), add=TRUE, cols="red", pch=16, cex=0.5)

par(op)
```

```{r Boundary,include=FALSE}
X <- XSeverity_manCity[[1]]
W <- as.owin(domain(X))


xbreak <- seq(W$xrange[1], W$xrange[2], length.out = 4)
ybreak <- seq(W$yrange[1], W$yrange[2], length.out = 5)

plot(X, main="X_manCity with grid", axes=TRUE)

# grid
abline(v = xbreak, h = ybreak, col="grey60", lty=2)
```

```{r}
library(sf)

# （lon, lat）
pts <- data.frame(
  name = c("N", "S", "E", "W"),
  lon  = c(-2.249197, -2.242401, -2.217505, -2.262179),
  lat  = c(53.489489, 53.469653, 53.476650, 53.477885)
)

pts_27700 <- st_as_sf(pts, coords = c("lon","lat"), crs = 4326) |>
  st_transform(27700)

#  points under projection 27700 （Easting, Northing）
cbind(pts["name"], st_coordinates(pts_27700))

pts_27700
```

```{r subnetwork, fig.width=8, fig.height=6,,dpi = 600}
# Wsub <- owin(xrange = c(382000, xbreak[3]),
#                  yrange = c(395000, ybreak[4]))
Wsub <- owin(xrange = c(382696, 385661),
                 yrange = c(397018, 399226))

X_sub <- vector("list", 3) # X_sub
for (i in seq_len(3)){
  X_sub[[i]] <- XSeverity_manCity[[i]][Wsub, clip = TRUE, drop = TRUE]
}


dir.create("0313Fri/CM_data", showWarnings = FALSE)
# save
saveRDS(X_sub, file = "0313Fri/CM_data/X_sub.rds")


# 取该对象的网络与窗口
L <- domain(X_sub[[1]])

op <- par(mar=c(1,1,1,1))

#pdf("Man_map.pdf",width=8, height=6)

plot(L, main="Accident with different severity on Manchester city center", col="grey70", lwd=0.4)


plot(as.ppp(X_sub[[3]]), add=TRUE, cols="green", pch=16, cex=0.5)
plot(as.ppp(X_sub[[2]]), add=TRUE, cols="blue", pch=16, cex=0.5)
plot(as.ppp(X_sub[[1]]), add=TRUE, cols="red", pch=16, cex=0.5)



usr <- par("usr")  # c(xmin, xmax, ymin, ymax)

x0 <- usr[1] + 0.08*(usr[2]-usr[1])
y0 <- usr[3] + 0.08*(usr[4]-usr[3])

sb <- spatstat.geom::yardstick(
  x0 = x0, y0 = y0,
  x1 = x0 + 1000, y1 = y0,   # 1000m measuring scale
  txt = "1000 m"
)

plot(sb, add = TRUE)

par(op)

#dev.off()
```

```{r IntensityEstimating, fig.width=8, fig.height=6,,dpi = 600}
if (!exists("X_sub")) {
  X_sub <- readRDS("0313Fri/CM_data/X_sub.rds")
}

severity_labs <- c("Severity 1(Lower)", "Severity 2", "Severity 3(Higher)")
severity_cols <- c("red", "blue", "green")
#severity_cols <- c("#E69F00", "#0072B2", "#CC79A7")

sigma_m <- 250

lambda_sub <- vector("list", length(X_sub))
for (i in seq_along(X_sub)) {
  lambda_sub[[i]] <- density(
    X_sub[[i]],
    sigma = sigma_m,
    distance = "path",
    continuous = TRUE,
    kernel = "gaussian",
    finespacing = FALSE,
    verbose = FALSE
  )
}

#pdf("test.pdf",width=15, height=10)
#op <- par(mfrow = c(6, 2), mar = c(0.5, 0.5, 2, 0.5))

for (i in seq_along(lambda_sub)) {
  plot(
    lambda_sub[[i]],
    
    main = paste0(severity_labs[i], ": kernel intensity, sigma = ", sigma_m, "m")
  )
  plot(
    lambda_sub[[i]],
    add = FALSE, 
    style = "w",
    main = paste0(severity_labs[i], ": kernel intensity, sigma = ", sigma_m, "m")
  )
  plot(
    as.ppp(X_sub[[i]]),
    add = TRUE,
    cols = severity_cols[i],
    pch = 16,
    cex = 0.5
  )
}
#par(op)
###############change the sigma

sigma_m <- 500

#op <- par(mfrow = c(6, 2), mar = c(0.5, 0.5, 2, 0.5))

lambda_sub <- vector("list", length(X_sub))
for (i in seq_along(X_sub)) {
  lambda_sub[[i]] <- density(
    X_sub[[i]],
    sigma = sigma_m,
    distance = "path",
    continuous = TRUE,
    kernel = "gaussian",
    finespacing = FALSE,
    verbose = FALSE
  )
}
for (i in seq_along(lambda_sub)) {
  plot(
    lambda_sub[[i]],
    
    main = paste0(severity_labs[i], ": kernel intensity, sigma = ", sigma_m, "m")
  )
  plot(
    lambda_sub[[i]],
    add = FALSE, 
    style = "w",
    main = paste0(severity_labs[i], ": kernel intensity, sigma = ", sigma_m, "m")
  )
  plot(
    as.ppp(X_sub[[i]]),
    add = TRUE,
    cols = severity_cols[i],
    pch = 16,
    cex = 0.5
  )
}

#par(op)
#dev.off()
```

```{r}
class(X_sub[[1]])
getS3method("density", "lpp")
args(getS3method("density", "lpp"))
```

```{r Compare with Voronoi,fig.width=8, fig.height=6,,dpi = 600}

lambda_vor <- vector("list", length(X_sub))
for (i in seq_along(X_sub)) {
  lambda_vor[[i]] <- densityVoronoi(
    X_sub[[i]],
    f = 1,
    metric = "shortestpath",
    verbose = FALSE
  )
}

for (i in seq_along(lambda_sub)){
  plot(
    lambda_vor[[i]],
    
    main = "Voronoi intensity on linear network"
  )
  plot(
    lambda_vor[[i]],
    add = FALSE, 
    style = "w",
    main = "Voronoi intensity on linear network"
  )
  plot(
    as.ppp(X_sub[[i]]),
    add = TRUE,
    pch = 16,
    cols = severity_cols[i],
    cex = 0.5
  )
}

```
