---
title: "WA_Sim"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r ,include=FALSE}
if (!require("spatstat.Knet")) {
  # Install the latest version of the package
  install.packages("spatstat.Knet_1.11-0.tar.gz", repos = NULL, type = "source")
  if (!require("spatstat.Knet")) 
    stop("Unable to install package")
} else requireversion(spatstat.Knet, "1.11-0")

library(spatstat.geom)
library(spatstat.linnet)
library(spatstat)
library(sf)        # 
library(dplyr)     # 

# Data Loading -----------------------------------------------------------------
data("wacrashes", package = "spatstat.Knet")
X_sub1 <- readRDS("Rakshit/WAsub_data/X_sub.rds")
X_sub2 <- readRDS("Rakshit/WAsub_data2/X_sub.rds")
```

## Original Simulation

```{r}

```

```{r}
L <- domain(X_sub2)      # 例如从已存在的 lpp 提取线网
r_grid <- seq(0, 20000, length = 100) # meter

# 叠加绘制 i 次 K 函数
B    <- 10                                # 重复次数（改成你要的 i）
n0   <- 70                               # 每次模拟的点数
cols <- grDevices::hcl.colors(B, "Dark 3")

for (b in seq_len(B)) {
  set.seed(n0 + b)
  X_sim   <- runiflpp(n0, L)              # 若想随次数递增，用 n0 * b
  Kb      <- Knet(X_sim, r = r_grid)

  if (b == 1) {
    plot(Kb, legend = FALSE, lwd = 2, col = cols[b], main = "")
  } else {
    plot(Kb, add = TRUE, legend = FALSE, lwd = 2, col = cols[b])
  }
}

legend("topleft",
       legend = paste0("sim ", seq_len(B)),
       col = cols, lwd = 2, bty = "n")
```

```{r}
for (b in seq_len(B)){
  set.seed(n0 + b)
  X_sim   <- runiflpp(n0, L)              # 若想随次数递增，用 n0 * b
  plot(X_sim)
}
```

### Confidence Interval

```{r}
L <- domain(X_sub2)      # 例如从已存在的 lpp 提取线网
r_grid <- seq(0, 20000, length = 101) # meter

# 叠加绘制 i 次 K 函数
B    <- 100                                # 重复次数（改成你要的 i）
n0   <- 300                               # 每次模拟的点数
cols <- grDevices::hcl.colors(B, "Dark 3")

for (b in seq_len(B)) {
  X_sim   <- runiflpp(n0, L)              # 若想随次数递增，用 n0 * b
  Kb      <- Knet(X_sim, r = r_grid)$est

  if (b == 1) {
    kfuns1 <- c()
    kfuns1 <- cbind(kfuns1,Kb)
    #plot(Kb, legend = FALSE, lwd = 2, col = cols[b], main = "")
  } else {
    kfuns1 <- cbind(kfuns1,Kb)
    #plot(Kb, add = TRUE, legend = FALSE, lwd = 2, col = cols[b])
  }
}

qts <- apply(kfuns1, 1, quantile, probs = c(0.025, 0.975))


plot(NULL, xlab = "r", ylab = "Estimated K function", xlim = range(r_grid), ylim = range(kfuns1))

polygon(c(r_grid, rev(r_grid)), c(qts[1, ], rev(qts[2, ])), col = "lightgrey", border = NA)

k_med <- apply(kfuns1, 1, median)      # 或 k_mean <- rowMeans(kfun1)
k_mean <- rowMeans(kfuns1)
lines(r_grid, k_med, lwd = 2, col = "red")
lines(r_grid, k_mean, lwd = 2, col = "blue")
#plot(Knet(X_sim), add = TRUE, legend = FALSE, lwd = 2)
```

### Increasing the number of Simulating points

```{r}
L <- domain(X_sub2)      # 例如从已存在的 lpp 提取线网
r_grid <- seq(0, 20000, length = 100) # meter

# 叠加绘制 i 次 K 函数
B    <- 50                                # 重复次数（改成你要的 i）
n0   <- 70                               # 每次模拟的点数
cols <- grDevices::hcl.colors(B, "Dark 3")

for (b in seq_len(B)) {
  set.seed(n0 + b)
  X_sim   <- runiflpp(n0 + (50* b), L)              # 若想随次数递增，用 n0 * b
  Kb      <- Knet(X_sim, r = r_grid)
  if((b - 1) %% 5 == 0){
    plot(Kb, legend = FALSE, lwd = 2, col = cols[((b - 1) %% 5) * 10 + 1], main = "")
  }else{
    plot(Kb, add = TRUE, legend = FALSE, lwd = 2, col = cols[((b - 1) %% 5) * 10 + 1])
  }
  if (b %% 5 == 0) {
    legend("topleft",
           legend = paste0("sim", (b-4):b,"      points level: ",seq(from = (n0 + (50* (b-4))), to = (n0 + (50* b)), by = 50)),
           
           col    = cols[ seq(from = 1, to = 41, by = 10) ],
           lwd    = 2,
           bty    = "n")
  }
}

```

```{r}
for (b in seq(1, B, by = 5)){
  set.seed(n0 + b)
  X_sim   <- runiflpp(n0, L)              # 若想随次数递增，用 n0 * b
  plot(X_sim, main = paste0("Points: ", n0 + 10*b))
}

```
